version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SPRING_DATASOURCE_URL=${{ secrets.RENDER_SPRING_DATASOURCE_URL }}
      - SPRING_DATASOURCE_USERNAME=${{ secrets.RENDER_SPRING_DATASOURCE_USERNAME }}
      - SPRING_DATASOURCE_PASSWORD=${{ secrets.RENDER_SPRING_DATASOURCE_PASSWORD }}
    ports:
      - 8080:8080