version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SPRING_DATASOURCE_URL=jdbc:sqlserver://rbaun.database.windows.net:1433;database=banking_db
      - SPRING_DATASOURCE_USERNAME=visitor@rbaun
      - SPRING_DATASOURCE_PASSWORD=banking123!
    ports:
      - 8080:8080