name: Run tests

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    name: Run unit and integration tests
    steps:
      - uses: actions/checkout@master
      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - run: mvn -f pom.xml test
